name: CI

on:
  push:
  pull_request:

jobs:
  run-tests:
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version:
          - "3.10"
          - "3.11"
    
    name: Test
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Atualizar pip
        run: python -m pip install --upgrade pip

      - name: Install dependences
        run: python -m pip install -r ./dev/docker/requirements.txt

# -------------------------------------------------------------------------------------------------------
      - name: Run Pytest
        run: pytest ./dev/script/app/py_test

      - name: Run Ruff
        run: ruff format ./dev/script/app
      
      - name: Run Mypy
        run: mypy ./dev/script/app --ignore-missing-imports --follow-imports skip
      
      - name: Run Flake
        run: flake8  --max-complexity 12 ./dev/script/app

# -------------------------------------------------------------------------------------------------------
      - name: Run Pytest aula
        run: pytest ./dev/script/app_testes/py_test
      
      - name: Run Ruff aula
        run: ruff format ./dev/script/app_testes

      - name: Run Mypy aula
        run: mypy ./dev/script/app_testes --ignore-missing-imports --follow-imports skip
      
      - name: Run Flake aula
        run: flake8  --max-complexity 12 ./dev/script/app_testes

# -------------------------------------------------------------------------------------------------------
      - name: Run Pytest pratica
        run: pytest ./dev/script/app_pratica/py_test
      
      - name: Run Ruff pratica
        run: ruff format ./dev/script/app_pratica

      - name: Run Mypy pratica
        run: mypy ./dev/script/app_pratica --ignore-missing-imports --follow-imports skip
      
      - name: Run Flake pratica
        run: flake8  --max-complexity 12 ./dev/script/app_pratica
